language: python
python: 3.4
sudo: true
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
  - sudo apt-get update -qq
  - sudo apt-get install -y libopenblas-dev liblapack-dev
install:
  - pip install tox
script:
  - travis_wait tox -v
notifications:
  email:
    on_success: never
    on_failure: always

