language: python
python: 3.5
sudo: required
dist: trusty
group: edge
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh
  - chmod +x miniconda3.sh
  - ./miniconda3.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n mrf anaconda
  - conda install --yes -n mrf pip
  - source activate mrf
install:
  - pwd
  - pip install -e `pwd`[test]
script:
  - py.test tests/ -s
notifications:
  email:
    on_success: always
    on_failure: always

