language: python
python: 2.7
sudo: required
dist: trusty
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=3
  - conda install --yes -n condaenv pip
  - source activate condaenv
install:
  - conda install --yes python=3 atlas numpy scipy matplotlib dateutil pandas pytest
  - pwd
  - pip install -e `pwd`
script:
  - py.test tests/
notifications:
  email:
    on_success: never
    on_failure: always

